### ISSUE TITLE
Stop Limit orders returns error -65, and does not execute

### ISSUE THREAD

**Issue by damgaard22** [day0market/pysterlingtrader#1]
Hi there,

Really interesting project, starred!

The limit and market order functions seems to be working just fine.
But the Stop (Only implemented in SterlingWrapper) and Stop Limit orders does not work.
They return status -65 on the submitOrder() calls.

Might this be due to the fact that i am using a Demo account, or have you gotten them to work without it?

Might also want to use:
`SterlingLib.STIPriceTypes.ptSTILmtStp;` in the Wrapper

But that didn't fix it.

**Comment by mikitowers** [comment]
HI @damgaard22  , firstly do you have resolve your issue???

For other hand I want to use this repo fot connect with my sterling account. 
I have one question, to connect the repo with the account, do I need run the Sterling app and run the main the repo and It´s all??

Great work of @day0market , amazing

**Comment by day0market** [comment]
@mikitowers You need to run sterling as administrator on your PC, otherwise sterling API will not work.

**Comment by day0market** [comment]
@damgaard22 -65 status is probably related to Sterling API permissions. Please ask your Sterling Provider about it. There is no such status in official docs https://download.sterlingtrader.com/documents/Sterling_ActiveX_API_Guide.pdf

**Comment by mikitowers** [comment]
> @mikitowers You need to run sterling as administrator on your PC, otherwise sterling API will not work.

Thanks for your answer @day0market, if I tell the true I had seen your answer now. Actually I send orders for stocks and options using c#, I left python because I need less time of execution. Now I have another problem and I´m searching the solution, How do I can send custom orders??? Send 2 orders as 1 order, execute the 2 orders or none.

Thanks for all.
